server:
  port: 8099
  address: localhost


spring:



  datasource:
    url: jdbc:mysql://localhost:3306/rapid_feedback?serverTimezone=UTC
    username: root
    password: 123
    dbcp2:
      test-while-idle: true
      validalstion-query: SELECT 1