server:
  port: 8099
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rapid_feedback?serverTimezone=UTC
    username: root
    password: spider0713
    dbcp2:
      test-while-idle: true
      validalstion-query: SELECT 1