server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ycca1?serverTimezone=UTC
    username: root
    password: 123
    dbcp2:
      test-while-idle: true
      validalstion-query: SELECT 1